// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run through a direct (non-pooled) connection when available —
    // pooled connections can leave advisory locks stuck mid-deploy (P1002).
    // Falls back to DATABASE_URL until DIRECT_URL is set in Vercel.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
